# Dockerfile
## Build application and create virtual environment
FROM python:3.9-slim-buster AS venv

# Install build dependences
RUN apt-get update && apt-get install -y curl

# Install poetry for dependency management
ENV POETRY_HOME=/opt/poetry
ENV PATH="${POETRY_HOME}/bin:${PATH}"
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3 -

## remove the below
#ENV POETRY_VERSION=1.6
#RUN curl -sSL curl -sSL https://install.python-poetry.org | python3 -
#ENV PATH /root/.poetry/bin:$PATH

WORKDIR /app

# Copy the dependency files
COPY pyproject.toml poetry.lock

# Install dependencies within a virtual environment
RUN python -m venv --copies /app/venv
RUN . /app/venv/bin/activate && poetry install

## Begin runtime image
FROM python:3.9-slim-buster AS prod

# Copy virtual environment from venv
COPY --from=venv /app/venv /app/venv/
ENV PATH /app/venv/bin:$PATH

WORKDIR /app

# Copy application code
COPY . ./

# Expose the port for app
EXPOSE 8000

# Healthcheck for app
HEALTHCHECK --start-period=30s CMD python -c "import requests; requests.get('http://localhost:8000', timeout=2)"

# Run the FastAPI app
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
