---
apiVersion: v1
kind: Service
metadata:
  name: lab4
  namespace: w255
  labels:
    app: lab4
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: lab4